%%----------------------------------------------------
%% Robot handle
%%
%% @author Rolong<erlang6@qq.com>
%%----------------------------------------------------
-module(robot_test_h).
-export([handle/3]).

-include("common.hrl").
-include("robot.hrl").

-define(receipt1, <<"ewoJInNpZ25hdHVyZSIgPSAiQW1kdTE4cVkxeHhwdE9VUDhvMEZNQ1Ixd0pGZkFm
eFpPN2hTcnF4QmlXcDIzc25NMU5zYUlhWm8xOGFzeDFlM0NqeHdyQU1QRjI1T0dR
d0lZRWUxTXBWZi9XZk5JK0xiaFg0NnExdXpncXU4TGRUeHZKUXhSaEJkZnlzMUVQ
NE9Za2duYkhSWFlTTzMrNWhKSVY5Z2hCTzY0MGRnM1cxYkpLdnpkdWR2SGxKNUFB
QURWekNDQTFNd2dnSTdvQU1DQVFJQ0NHVVVrVTNaV0FTMU1BMEdDU3FHU0liM0RR
RUJCUVVBTUg4eEN6QUpCZ05WQkFZVEFsVlRNUk13RVFZRFZRUUtEQXBCY0hCc1pT
QkpibU11TVNZd0pBWURWUVFMREIxQmNIQnNaU0JEWlhKMGFXWnBZMkYwYVc5dUlF
RjFkR2h2Y21sMGVURXpNREVHQTFVRUF3d3FRWEJ3YkdVZ2FWUjFibVZ6SUZOMGIz
SmxJRU5sY25ScFptbGpZWFJwYjI0Z1FYVjBhRzl5YVhSNU1CNFhEVEE1TURZeE5U
SXlNRFUxTmxvWERURTBNRFl4TkRJeU1EVTFObG93WkRFak1DRUdBMVVFQXd3YVVI
VnlZMmhoYzJWU1pXTmxhWEIwUTJWeWRHbG1hV05oZEdVeEd6QVpCZ05WQkFzTUVr
RndjR3hsSUdsVWRXNWxjeUJUZEc5eVpURVRNQkVHQTFVRUNnd0tRWEJ3YkdVZ1NX
NWpMakVMTUFrR0ExVUVCaE1DVlZNd2daOHdEUVlKS29aSWh2Y05BUUVCQlFBRGdZ
MEFNSUdKQW9HQkFNclJqRjJjdDRJclNkaVRDaGFJMGc4cHd2L2NtSHM4cC9Sd1Yv
cnQvOTFYS1ZoTmw0WElCaW1LalFRTmZnSHNEczZ5anUrK0RyS0pFN3VLc3BoTWRk
S1lmRkU1ckdYc0FkQkVqQndSSXhleFRldngzSExFRkdBdDFtb0t4NTA5ZGh4dGlJ
ZERnSnYyWWFWczQ5QjB1SnZOZHk2U01xTk5MSHNETHpEUzlvWkhBZ01CQUFHamNq
QndNQXdHQTFVZEV3RUIvd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVVOaDNvNHAyQzBn
RVl0VEpyRHRkREM1RllRem93RGdZRFZSMFBBUUgvQkFRREFnZUFNQjBHQTFVZERn
UVdCQlNwZzRQeUdVakZQaEpYQ0JUTXphTittVjhrOVRBUUJnb3Foa2lHOTJOa0Jn
VUJCQUlGQURBTkJna3Foa2lHOXcwQkFRVUZBQU9DQVFFQUVhU2JQanRtTjRDL0lC
M1FFcEszMlJ4YWNDRFhkVlhBZVZSZVM1RmFaeGMrdDg4cFFQOTNCaUF4dmRXLzNl
VFNNR1k1RmJlQVlMM2V0cVA1Z204d3JGb2pYMGlreVZSU3RRKy9BUTBLRWp0cUIw
N2tMczlRVWU4Y3pSOFVHZmRNMUV1bVYvVWd2RGQ0TndOWXhMUU1nNFdUUWZna1FR
Vnk4R1had1ZIZ2JFL1VDNlk3MDUzcEdYQms1MU5QTTN3b3hoZDNnU1JMdlhqK2xv
SHNTdGNURXFlOXBCRHBtRzUrc2s0dHcrR0szR01lRU41LytlMVFUOW5wL0tsMW5q
K2FCdzdDMHhzeTBiRm5hQWQxY1NTNnhkb3J5L0NVdk02Z3RLc21uT09kcVRlc2Jw
MGJzOHNuNldxczBDOWRnY3hSSHVPTVoydG04bnBMVW03YXJnT1N6UT09IjsKCSJw
dXJjaGFzZS1pbmZvIiA9ICJld29KSW05eWFXZHBibUZzTFhCMWNtTm9ZWE5sTFdS
aGRHVXRjSE4wSWlBOUlDSXlNREUwTFRBeExUQTJJREl6T2pJMU9qUXlJRUZ0WlhK
cFkyRXZURzl6WDBGdVoyVnNaWE1pT3dvSkluVnVhWEYxWlMxcFpHVnVkR2xtYVdW
eUlpQTlJQ0prWW1aa016RTNPVGN4TjJJeVlXVmhaakl6WVRBd01qTTJPV00xTnpj
MFpqVTFabVpqTmpBMklqc0tDU0p2Y21sbmFXNWhiQzEwY21GdWMyRmpkR2x2Ymkx
cFpDSWdQU0FpTVRBd01EQXdNREE1TnpnNE5qQTFPU0k3Q2draVluWnljeUlnUFNB
aU1TNHdMakFpT3dvSkluUnlZVzV6WVdOMGFXOXVMV2xrSWlBOUlDSXhNREF3TURB
d01EazNPRGcyTURVNUlqc0tDU0p4ZFdGdWRHbDBlU0lnUFNBaU1TSTdDZ2tpYjNK
cFoybHVZV3d0Y0hWeVkyaGhjMlV0WkdGMFpTMXRjeUlnUFNBaU1UTTRPVEEzT1RV
ME1qQTNNaUk3Q2draWRXNXBjWFZsTFhabGJtUnZjaTFwWkdWdWRHbG1hV1Z5SWlB
OUlDSTROVEl6TWtZeE15MUNPRGt3TFRReE9Ua3RRVE5ETkMweU0wRkdSVGswUTBR
NU56TWlPd29KSW5CeWIyUjFZM1F0YVdRaUlEMGdJbU52YlM1dGMzUXVaR2xoYlc5
dVpGOHhNakFpT3dvSkltbDBaVzB0YVdRaUlEMGdJamM1TWpZek1EVXdOU0k3Q2dr
aVltbGtJaUE5SUNKamIyMHVkSFZ5WW05MFpXTm9MbTFsYm1kemFHOTFkR0Z1WnlJ
N0Nna2ljSFZ5WTJoaGMyVXRaR0YwWlMxdGN5SWdQU0FpTVRNNE9UQTNPVFUwTWpB
M01pSTdDZ2tpY0hWeVkyaGhjMlV0WkdGMFpTSWdQU0FpTWpBeE5DMHdNUzB3TnlB
d056b3lOVG8wTWlCRmRHTXZSMDFVSWpzS0NTSndkWEpqYUdGelpTMWtZWFJsTFhC
emRDSWdQU0FpTWpBeE5DMHdNUzB3TmlBeU16b3lOVG8wTWlCQmJXVnlhV05oTDB4
dmMxOUJibWRsYkdWeklqc0tDU0p2Y21sbmFXNWhiQzF3ZFhKamFHRnpaUzFrWVhS
bElpQTlJQ0l5TURFMExUQXhMVEEzSURBM09qSTFPalF5SUVWMFl5OUhUVlFpT3dw
OSI7CgkiZW52aXJvbm1lbnQiID0gIlNhbmRib3giOwoJInBvZCIgPSAiMTAwIjsK
CSJzaWduaW5nLXN0YXR1cyIgPSAiMCI7Cn0=">>).

-define(receipt2, <<"ewoJInNpZ25hdHVyZSIgPSAiQWxFdTZ3T2hISnlIK0poVW9KVmg4cWt0UVJGMDdh
RnY1cCt2WjJmUWJrZ081MkdWQjFBUDMwTHNOU0RVMytxU2JnTUlabmV6MGtZY1Vu
UVJLR3ZhVGluTmxobXZWaEh1WS9jQko3ZzJidW9kWThwRGRyQ09CM3NYaVg5QTNt
ZTFLcnFIV2UwT2VweTQzcm81bHVIaDg3c0FpbkE4cHdUalVkTnFjVkZVa2MzU0FB
QURWekNDQTFNd2dnSTdvQU1DQVFJQ0NHVVVrVTNaV0FTMU1BMEdDU3FHU0liM0RR
RUJCUVVBTUg4eEN6QUpCZ05WQkFZVEFsVlRNUk13RVFZRFZRUUtEQXBCY0hCc1pT
QkpibU11TVNZd0pBWURWUVFMREIxQmNIQnNaU0JEWlhKMGFXWnBZMkYwYVc5dUlF
RjFkR2h2Y21sMGVURXpNREVHQTFVRUF3d3FRWEJ3YkdVZ2FWUjFibVZ6SUZOMGIz
SmxJRU5sY25ScFptbGpZWFJwYjI0Z1FYVjBhRzl5YVhSNU1CNFhEVEE1TURZeE5U
SXlNRFUxTmxvWERURTBNRFl4TkRJeU1EVTFObG93WkRFak1DRUdBMVVFQXd3YVVI
VnlZMmhoYzJWU1pXTmxhWEIwUTJWeWRHbG1hV05oZEdVeEd6QVpCZ05WQkFzTUVr
RndjR3hsSUdsVWRXNWxjeUJUZEc5eVpURVRNQkVHQTFVRUNnd0tRWEJ3YkdVZ1NX
NWpMakVMTUFrR0ExVUVCaE1DVlZNd2daOHdEUVlKS29aSWh2Y05BUUVCQlFBRGdZ
MEFNSUdKQW9HQkFNclJqRjJjdDRJclNkaVRDaGFJMGc4cHd2L2NtSHM4cC9Sd1Yv
cnQvOTFYS1ZoTmw0WElCaW1LalFRTmZnSHNEczZ5anUrK0RyS0pFN3VLc3BoTWRk
S1lmRkU1ckdYc0FkQkVqQndSSXhleFRldngzSExFRkdBdDFtb0t4NTA5ZGh4dGlJ
ZERnSnYyWWFWczQ5QjB1SnZOZHk2U01xTk5MSHNETHpEUzlvWkhBZ01CQUFHamNq
QndNQXdHQTFVZEV3RUIvd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVVOaDNvNHAyQzBn
RVl0VEpyRHRkREM1RllRem93RGdZRFZSMFBBUUgvQkFRREFnZUFNQjBHQTFVZERn
UVdCQlNwZzRQeUdVakZQaEpYQ0JUTXphTittVjhrOVRBUUJnb3Foa2lHOTJOa0Jn
VUJCQUlGQURBTkJna3Foa2lHOXcwQkFRVUZBQU9DQVFFQUVhU2JQanRtTjRDL0lC
M1FFcEszMlJ4YWNDRFhkVlhBZVZSZVM1RmFaeGMrdDg4cFFQOTNCaUF4dmRXLzNl
VFNNR1k1RmJlQVlMM2V0cVA1Z204d3JGb2pYMGlreVZSU3RRKy9BUTBLRWp0cUIw
N2tMczlRVWU4Y3pSOFVHZmRNMUV1bVYvVWd2RGQ0TndOWXhMUU1nNFdUUWZna1FR
Vnk4R1had1ZIZ2JFL1VDNlk3MDUzcEdYQms1MU5QTTN3b3hoZDNnU1JMdlhqK2xv
SHNTdGNURXFlOXBCRHBtRzUrc2s0dHcrR0szR01lRU41LytlMVFUOW5wL0tsMW5q
K2FCdzdDMHhzeTBiRm5hQWQxY1NTNnhkb3J5L0NVdk02Z3RLc21uT09kcVRlc2Jw
MGJzOHNuNldxczBDOWRnY3hSSHVPTVoydG04bnBMVW03YXJnT1N6UT09IjsKCSJw
dXJjaGFzZS1pbmZvIiA9ICJld29KSW05eWFXZHBibUZzTFhCMWNtTm9ZWE5sTFdS
aGRHVXRjSE4wSWlBOUlDSXlNREUwTFRBeExUQTRJREF3T2pJd09qVXpJRUZ0WlhK
cFkyRXZURzl6WDBGdVoyVnNaWE1pT3dvSkluVnVhWEYxWlMxcFpHVnVkR2xtYVdW
eUlpQTlJQ0prWW1aa016RTNPVGN4TjJJeVlXVmhaakl6WVRBd01qTTJPV00xTnpj
MFpqVTFabVpqTmpBMklqc0tDU0p2Y21sbmFXNWhiQzEwY21GdWMyRmpkR2x2Ymkx
cFpDSWdQU0FpTVRBd01EQXdNREE1TnprNU5UY3pPQ0k3Q2draVluWnljeUlnUFNB
aU1TNHdMakFpT3dvSkluUnlZVzV6WVdOMGFXOXVMV2xrSWlBOUlDSXhNREF3TURB
d01EazNPVGsxTnpNNElqc0tDU0p4ZFdGdWRHbDBlU0lnUFNBaU1TSTdDZ2tpYjNK
cFoybHVZV3d0Y0hWeVkyaGhjMlV0WkdGMFpTMXRjeUlnUFNBaU1UTTRPVEUyT1RJ
MU16STROaUk3Q2draWRXNXBjWFZsTFhabGJtUnZjaTFwWkdWdWRHbG1hV1Z5SWlB
OUlDSXdORE5CUWpsQ05TMHdORUZCTFRReU1UVXRRVFl5UVMwMU9UWTNOak0wUTBV
MU9UTWlPd29KSW5CeWIyUjFZM1F0YVdRaUlEMGdJbU52YlM1dGMzUXVaR2xoYlc5
dVpGOHhOVGsyT0NJN0Nna2lhWFJsYlMxcFpDSWdQU0FpTnpreU5qTTNOVGN3SWpz
S0NTSmlhV1FpSUQwZ0ltTnZiUzUwZFhKaWIzUmxZMmd1YldWdVozTm9iM1YwWVc1
bklqc0tDU0p3ZFhKamFHRnpaUzFrWVhSbExXMXpJaUE5SUNJeE16ZzVNVFk1TWpV
ek1qZzJJanNLQ1NKd2RYSmphR0Z6WlMxa1lYUmxJaUE5SUNJeU1ERTBMVEF4TFRB
NElEQTRPakl3T2pVeklFVjBZeTlIVFZRaU93b0pJbkIxY21Ob1lYTmxMV1JoZEdV
dGNITjBJaUE5SUNJeU1ERTBMVEF4TFRBNElEQXdPakl3T2pVeklFRnRaWEpwWTJF
dlRHOXpYMEZ1WjJWc1pYTWlPd29KSW05eWFXZHBibUZzTFhCMWNtTm9ZWE5sTFdS
aGRHVWlJRDBnSWpJd01UUXRNREV0TURnZ01EZzZNakE2TlRNZ1JYUmpMMGROVkNJ
N0NuMD0iOwoJImVudmlyb25tZW50IiA9ICJTYW5kYm94IjsKCSJwb2QiID0gIjEw
MCI7Cgkic2lnbmluZy1zdGF0dXMiID0gIjAiOwp9">>).

-define(receipt3, <<"ewoJInNpZ25hdHVyZSIgPSAiQWoyWWd4Q0dIMzJxZVE1WnlvTjhSTnVLQmZkUk40
WERWcFRsMVdUTzdPVUMybDFKSjFPU21xNEQxYmovZGNobnROb1pSV1VUZm02YlpW
QkVGQzFpeWovUG1TaXF3cWlWVHRybzExVmxjdUN2NWNvMHdjeDZmWHhYYXBKOE5y
Q3hNZzZJbjYwOW80UWVITWxzaDNWcGdFdGV2ZUc1SWhKTE1CTUh3YWxxZVd5NEFB
QURWekNDQTFNd2dnSTdvQU1DQVFJQ0NHVVVrVTNaV0FTMU1BMEdDU3FHU0liM0RR
RUJCUVVBTUg4eEN6QUpCZ05WQkFZVEFsVlRNUk13RVFZRFZRUUtEQXBCY0hCc1pT
QkpibU11TVNZd0pBWURWUVFMREIxQmNIQnNaU0JEWlhKMGFXWnBZMkYwYVc5dUlF
RjFkR2h2Y21sMGVURXpNREVHQTFVRUF3d3FRWEJ3YkdVZ2FWUjFibVZ6SUZOMGIz
SmxJRU5sY25ScFptbGpZWFJwYjI0Z1FYVjBhRzl5YVhSNU1CNFhEVEE1TURZeE5U
SXlNRFUxTmxvWERURTBNRFl4TkRJeU1EVTFObG93WkRFak1DRUdBMVVFQXd3YVVI
VnlZMmhoYzJWU1pXTmxhWEIwUTJWeWRHbG1hV05oZEdVeEd6QVpCZ05WQkFzTUVr
RndjR3hsSUdsVWRXNWxjeUJUZEc5eVpURVRNQkVHQTFVRUNnd0tRWEJ3YkdVZ1NX
NWpMakVMTUFrR0ExVUVCaE1DVlZNd2daOHdEUVlKS29aSWh2Y05BUUVCQlFBRGdZ
MEFNSUdKQW9HQkFNclJqRjJjdDRJclNkaVRDaGFJMGc4cHd2L2NtSHM4cC9Sd1Yv
cnQvOTFYS1ZoTmw0WElCaW1LalFRTmZnSHNEczZ5anUrK0RyS0pFN3VLc3BoTWRk
S1lmRkU1ckdYc0FkQkVqQndSSXhleFRldngzSExFRkdBdDFtb0t4NTA5ZGh4dGlJ
ZERnSnYyWWFWczQ5QjB1SnZOZHk2U01xTk5MSHNETHpEUzlvWkhBZ01CQUFHamNq
QndNQXdHQTFVZEV3RUIvd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVVOaDNvNHAyQzBn
RVl0VEpyRHRkREM1RllRem93RGdZRFZSMFBBUUgvQkFRREFnZUFNQjBHQTFVZERn
UVdCQlNwZzRQeUdVakZQaEpYQ0JUTXphTittVjhrOVRBUUJnb3Foa2lHOTJOa0Jn
VUJCQUlGQURBTkJna3Foa2lHOXcwQkFRVUZBQU9DQVFFQUVhU2JQanRtTjRDL0lC
M1FFcEszMlJ4YWNDRFhkVlhBZVZSZVM1RmFaeGMrdDg4cFFQOTNCaUF4dmRXLzNl
VFNNR1k1RmJlQVlMM2V0cVA1Z204d3JGb2pYMGlreVZSU3RRKy9BUTBLRWp0cUIw
N2tMczlRVWU4Y3pSOFVHZmRNMUV1bVYvVWd2RGQ0TndOWXhMUU1nNFdUUWZna1FR
Vnk4R1had1ZIZ2JFL1VDNlk3MDUzcEdYQms1MU5QTTN3b3hoZDNnU1JMdlhqK2xv
SHNTdGNURXFlOXBCRHBtRzUrc2s0dHcrR0szR01lRU41LytlMVFUOW5wL0tsMW5q
K2FCdzdDMHhzeTBiRm5hQWQxY1NTNnhkb3J5L0NVdk02Z3RLc21uT09kcVRlc2Jw
MGJzOHNuNldxczBDOWRnY3hSSHVPTVoydG04bnBMVW03YXJnT1N6UT09IjsKCSJw
dXJjaGFzZS1pbmZvIiA9ICJld29KSW05eWFXZHBibUZzTFhCMWNtTm9ZWE5sTFdS
aGRHVXRjSE4wSWlBOUlDSXlNREUwTFRBeUxUQTJJREl4T2pVME9qTTVJRUZ0WlhK
cFkyRXZURzl6WDBGdVoyVnNaWE1pT3dvSkluQjFjbU5vWVhObExXUmhkR1V0YlhN
aUlEMGdJakV6T1RFM05USTBOemt6TURBaU93b0pJblZ1YVhGMVpTMXBaR1Z1ZEds
bWFXVnlJaUE5SUNKak1EZGhOemd4WlRsbE1ERTFaVEEzTnpka056bGhZVFUzWVRk
aU5qVTNOVFF5TmpWbVlqZ3pJanNLQ1NKdmNtbG5hVzVoYkMxMGNtRnVjMkZqZEds
dmJpMXBaQ0lnUFNBaU56QXdNREF3T0RZek56azFPRGtpT3dvSkltSjJjbk1pSUQw
Z0lqRXVNQzR4SWpzS0NTSmhjSEF0YVhSbGJTMXBaQ0lnUFNBaU56ZzFPREl6T1Rr
eklqc0tDU0owY21GdWMyRmpkR2x2YmkxcFpDSWdQU0FpTnpBd01EQXdPRFl6Tnpr
MU9Ea2lPd29KSW5GMVlXNTBhWFI1SWlBOUlDSXhJanNLQ1NKdmNtbG5hVzVoYkMx
d2RYSmphR0Z6WlMxa1lYUmxMVzF6SWlBOUlDSXhNemt4TnpVeU5EYzVNekF3SWpz
S0NTSjFibWx4ZFdVdGRtVnVaRzl5TFdsa1pXNTBhV1pwWlhJaUlEMGdJall3Tmpj
NE4wSkZMVE5CUWpRdE5EYzBNeTFCUXpZeExUYzVNekpHUWpjNFJETXhPQ0k3Q2dr
aWFYUmxiUzFwWkNJZ1BTQWlOemt5TmpNd05qSTNJanNLQ1NKMlpYSnphVzl1TFdW
NGRHVnlibUZzTFdsa1pXNTBhV1pwWlhJaUlEMGdJakkyTVRNd01qWXpPU0k3Q2dr
aWNISnZaSFZqZEMxcFpDSWdQU0FpWTI5dExtMXpkQzVrYVdGdGIyNWtYek16TUNJ
N0Nna2ljSFZ5WTJoaGMyVXRaR0YwWlNJZ1BTQWlNakF4TkMwd01pMHdOeUF3TlRv
MU5Eb3pPU0JGZEdNdlIwMVVJanNLQ1NKdmNtbG5hVzVoYkMxd2RYSmphR0Z6WlMx
a1lYUmxJaUE5SUNJeU1ERTBMVEF5TFRBM0lEQTFPalUwT2pNNUlFVjBZeTlIVFZR
aU93b0pJbUpwWkNJZ1BTQWlZMjl0TG5SMWNtSnZkR1ZqYUM1dFpXNW5jMmh2ZFhS
aGJtY2lPd29KSW5CMWNtTm9ZWE5sTFdSaGRHVXRjSE4wSWlBOUlDSXlNREUwTFRB
eUxUQTJJREl4T2pVME9qTTVJRUZ0WlhKcFkyRXZURzl6WDBGdVoyVnNaWE1pT3dw
OSI7CgkicG9kIiA9ICI3IjsKCSJzaWduaW5nLXN0YXR1cyIgPSAiMCI7Cn0=">>).

login_ok(R) ->
    robot ! {login_ok, R#robot.aid, R#robot.id, self()},
    %% 赠送英雄
    R#robot.pid_sender ! {cmd, 14023, [30005]},
    %% 请求基础数据
    R#robot.pid_sender ! {cmd, 11003, []},
    %% 请求玩家所有英雄
    R#robot.pid_sender ! {cmd, 14002, []},
    %% 设置成长进度 (成长进度只能设置为大于或等于当前值)
    R#robot.pid_sender ! {cmd, 11010, [12]},
    %% 魔法宝珠状态
    %% R#robot.pid_sender ! {cmd, 13024, []},
    R#robot{pid = self()}.

%%' 10协议_登陆认证

handle(11000, [LoginState, Growth, Rid], R) ->
    %% ?INFO("11001:~w", [[LoginState, Growth, Rid]]),
    case LoginState of
        10 ->
            %% 注册成功，正常登陆
            io:format("1"),
            login_ok(R#robot{id = Rid, growth = Growth});
        20 ->
            %% 正常登陆
            io:format("2"),
            login_ok(R#robot{id = Rid, growth = Growth});
        22 ->
            %% 创建角色
            AidB = list_to_binary([?AID_PREFIX, integer_to_list(R#robot.aid)]),
            Key = "23d7f859778d2093",
            Rand = util:rand(0, 255),
            Signature = util:md5(list_to_binary([
                        "1"
                        ,integer_to_list(Rand)
                        ,Key
                        ,AidB
                    ])),
            R#robot.pid_sender ! {cmd, 11000, [1, Rand, 1, AidB, AidB, Signature]},
            ?DEBUG("[REG] Rid:~w AccId:~s", [Rid, AidB]),
            R#robot{sex = 0, name = <<>>};
        _ ->
            io:format("login failure! ~w~n", [[LoginState, Growth, Rid]]),
            R
    end;
%%.

handle(10011, [0], _R) ->
    ?INFO("in_app_purchase_ok !!!", []);
handle(10011, [1], _R) ->
    ?INFO("### in_app_purchase_error ###", []);

%% 基础数据
handle(11003, _, R) ->
    RecvReceipt = ?receipt3,
    R#robot.pid_sender ! {cmd, 10011, [<<>>, RecvReceipt]},
    ok;

%% 宝珠抽取状态
handle(13024, [Jewels], R) ->
    put('@jewel', 0),
    Lev = lists:foldl(fun
            ([Q, 1], RtQ) when Q > RtQ -> Q;
            (_, RtQ) -> RtQ
        end, 1, Jewels),
    R#robot.pid_sender ! {cmd, 13022, [Lev]},
    ok;

%% 魔法宝珠获取
handle(13022, [0, Lev, _Id, _Type], R) ->
    Index = get('@jewel'),
    case Index >= 1000000 of
        true ->
            ?INFO("[GET JEWEL] INDEX:~w", [Index]);
        false ->
            case Lev of
                5 ->
                    ?INFO("Index:~w", [Index + 1]),
                    put('@jewel', Index + 1),
                    ok;
                _ ->
                    put('@jewel', Index + 1),
                    ok
            end,
            case Lev > 0 of
                true -> R#robot.pid_sender ! {cmd, 13022, [Lev]};
                false -> R#robot.pid_sender ! {cmd, 13022, [1]}
            end
    end;

handle(13022, [Code, _Lev, _Id, _Type], _R) ->
    case Code of
        1 -> ?INFO("[GET JEWEL] No Gold!");
        2 -> ?INFO("[GET JEWEL] No Diamond!");
        3 -> ?INFO("[GET JEWEL] No Space!");
        _ -> ?INFO("[GET JEWEL] CODE:~w", [Code])
    end,
    ?INFO("[GET JEWEL] COUNT:~w", [get('@jewel')]),
    ok;

handle(_Cmd, _Data, _R) ->

    %% io:format("Recv [Cmd:~w Data:~w]~n", [Cmd, Data]).
    ok.

%%%%%%%%%%%%%%%%%%%%%



%%% vim: set filetype=erlang foldmarker=%%',%%. foldmethod=marker:
