<?php
## 日志类型定义

## let i=1|g/X/s//\=i/|let i=i+1

$log_type[ 0] = "== 全部 =="    ;
$log_type[ 1] = "强化"          ;
$log_type[ 2] = "镶嵌"          ;
$log_type[ 3] = "合成"          ;
$log_type[ 4] = "进阶"          ;
$log_type[ 5] = "吞噬"          ;
$log_type[ 6] = "扩充背包"      ;
$log_type[ 7] = "购买英雄"      ;
$log_type[ 8] = "抽取宝珠"      ;
$log_type[ 9] = "抽奖"          ;
$log_type[10] = "购买幸运星"    ;
$log_type[11] = "连续登陆"      ;
$log_type[12] = "关卡战斗"      ;
$log_type[13] = "副本战斗"      ;
$log_type[14] = "竞技场战斗"    ;
$log_type[15] = "竞技场反击"    ;
$log_type[16] = "竞技场宝箱"    ;
$log_type[17] = "竞技场俸禄"    ;
$log_type[18] = "酒馆刷新时间"  ;
$log_type[19] = "竞技场刷新时间";
$log_type[20] = "竞技场购买次数";
$log_type[21] = "发布悬赏次数"  ;
$log_type[22] = "揭榜次数"      ;
$log_type[23] = "悬赏奖励"      ;
$log_type[24] = "体力购买次数"  ;
$log_type[25] = "副本购买次数"  ;
$log_type[26] = "强化CD打破"    ;
$log_type[27] = "成就奖励"      ;
$log_type[28] = "商城购买"      ;
$log_type[29] = "物品出售"      ;
$log_type[30] = "净化"          ;
$log_type[31] = "后台加金币"    ;
$log_type[32] = "后台加钻石"    ;
$log_type[33] = "购买疲劳"      ;
$log_type[34] = "后台赠送"      ;
$log_type[35] = "充值购买"      ;
$log_type[36] = "邮件获得"      ;
$log_type[37] = "宝珠拆卸"      ;
$log_type[38] = "解雇英雄"      ;
$log_type[39] = "英雄携带数"    ;
$log_type[40] = "首充活动"      ;
$log_type[41] = "邀请用户数领奖";
$log_type[42] = "好友登录数领奖";
$log_type[43] = "邀请码领奖"    ;
$log_type[44] = "关卡礼包领奖"  ;
$log_type[45] = "注册礼包"      ;
$log_type[46] = "后台扣除"      ;
$log_type[47] = "首充双倍"      ;
$log_type[48] = "运营绑定激活码";
$log_type[49] = "月卡奖励"      ;
$log_type[50] = "定期活动奖励"  ;
$log_type[51] = "自定义活动奖励";
$log_type[52] = "vip每日礼包"   ;
$log_type[53] = "微信分享奖励"  ;
$log_type[54] = "评星奖励"      ;
$log_type[55] = "竞技场兑换"    ;
$log_type[56] = "vip邮件礼包"   ;
$log_type[57] = "关卡邮件礼包"  ;
$log_type[58] = "后台发送"      ;
$log_type[59] = "活动奖励"      ;
$log_type[60] = "宝珠升级"      ;
