{
	[
		'src/*'
		,'src/kernel/*'
		,'src/robot/*'
		,'src/data/*'
		,'src/json/*'
		,'src/test/*'
		,'src/pt/*'
		,'src/mod/*'
		,'src/lib/*'
		,'src/lib/mysql/*'
		,'src/lib/json/*'
	]
	,[
		debug_info
		,{i, "include"}
		,{outdir, "ebin"}
	]
}.
